export const ANOMALY_TYPES = {
  LOGIN_BRUTE_FORCE: 'LOGIN_BRUTE_FORCE',
  NEW_IP_LOGIN: 'NEW_IP_LOGIN',
  REQUEST_BURST: 'REQUEST_BURST',
  SUSPICIOUS_BULK_READ: 'SUSPICIOUS_BULK_READ',
  FORBIDDEN_OBJECT_ACCESS: 'FORBIDDEN_OBJECT_ACCESS',
} as const

export type AnomalyType = (typeof ANOMALY_TYPES)[keyof typeof ANOMALY_TYPES]
